import { EVENT_MAP } from "./types.js";

export const PMDDG_73X_HELPER_EVENTS = {
  OPEN_FAULT_MENU: [
    EVENT_MAP.CDU_R_MENU,
    EVENT_MAP.CDU_R_R4,
    EVENT_MAP.CDU_R_L1,
    EVENT_MAP.CDU_R_L3,
  ],
  CDU_NEXT_PAGE: [EVENT_MAP.CDU_R_NEXT_PAGE],
  CDU_EXECUTE: [EVENT_MAP.CDU_R_EXEC],
  CDU_ACTIVATE_FAULT: [EVENT_MAP.CDU_R_L1, EVENT_MAP.CDU_R_EXEC],
  CDU_PROGRAMMED_FAULT: [EVENT_MAP.CDU_R_L1],
};

export const PMDG_73X_CDU_COMMANDS = {
    'Engine 1 Failure': [
        ...PMDDG_73X_HELPER_EVENTS.OPEN_FAULT_MENU,
        ...PMDDG_73X_HELPER_EVENTS.CDU_NEXT_PAGE,
        EVENT_MAP.CDU_R_L2,
        ...PMDDG_73X_HELPER_EVENTS.CDU_PROGRAMMED_FAULT,
        EVENT_MAP.CDU_R_L3,
        ...PMDDG_73X_HELPER_EVENTS.CDU_ACTIVATE_FAULT,
        EVENT_MAP.CDU_R_MENU,
    ],
    'Engine 2 Failure': [
        ...PMDDG_73X_HELPER_EVENTS.OPEN_FAULT_MENU,
        ...PMDDG_73X_HELPER_EVENTS.CDU_NEXT_PAGE,
        EVENT_MAP.CDU_R_L2,
        ...PMDDG_73X_HELPER_EVENTS.CDU_PROGRAMMED_FAULT,
        EVENT_MAP.CDU_R_L4,
        ...PMDDG_73X_HELPER_EVENTS.CDU_ACTIVATE_FAULT,
        EVENT_MAP.CDU_R_MENU,
    ],
}