export interface PlaneEventHandler {
  activateEvent(eventName: string): void;
  stop(): void;
  start(): void;
}

export type AircraftEventsList = {
  aircraft: string;
  categories: EventCategory[];
};

export type EventCategory = {
  name: string;
  events: string[];
};

export const availableEvents = [
  {
    aircraft: "PMDG73X",
    categories: [
      {
        name: "Active",
        events: [],
      },
      {
        name: "All Systems",
        events: [],
      },
      {
        name: "APU",
        events: ["APU Air", "APU Severe"],
      },
      {
        name: "Automatic Flight",
        events: [
          "Autothrottle INOP",
          "Flight Control Channel A INOP",
          "Flight Control Channel B INOP",
          "Autoflight System INOP",
        ],
      },
      {
        name: "Doors",
        events: [
          "Air Stair Hatch",
          "Door 1Left",
          "Door 1Right",
          "Door 2Left",
          "Door 2Right",
          "Forward Cargo Door",
          "Aft Cargo Door",
        ],
      },
      {
        name: "Electrical",
        events: [
          "Integrated Drive Generator 1",
          "Integrated Drive Generator 2",
          "IDG 1 Drive",
          "IDG 2 Drive",
          "APU Generator",
          "Main Battery",
          "Main Battery Charger",
          "Aux Battery",
          "Aux Battery Charger",
          "Static Inverter",
          "Transformer Rectifier 1",
          "Transformer Rectifier 2",
          "Transformer Rectifier 3",
          "AC Transfer Bus 1",
          "AC Transfer Bus 2",
          "AC Main Bus 1",
          "AC Main Bus 2",
          "AC Galley Bus 1",
          "AC Galley Bus 2",
          "AC Standby Bus",
          "AC Ground Service Bus 1",
          "AC Ground Service Bus 2",
          "DC Bus 1",
          "DC Bus 2",
          "DC Standby Bus",
          "DC Ground Service Bus",
          "DC Hot Battery Bus",
          "DC Hot Battery Bus Switched",
          "DC Battery Bus",
        ],
      },
      {
        name: "Engine",
        events: [
          "Electronic Engine Computer 1",
          "Electronic Engine Computer 2",
          "Engine 1 Severe Damage",
          "Engine 2 Severe Damage",
          "Engine 1 Flame-Out",
          "Engine 2 Flame-Out",
          "Engine 1 EGT Exceedance",
          "Engine 2 EGT Exceedance",
          "Engine 1 Oil Leak",
          "Engine 2 Oil Leak",
          "Engine 1 Oil Pressure",
          "Engine 2 Oil Pressure",
          "Engine 1 Oil Temperature",
          "Engine 2 Oil Temperature",
          "Engine 1 Vibration",
          "Engine 2 Vibration",
          "Engine 1 V1-Cut",
          "Engine 2 V1-Cut",
          "Engine 1 Vr-Cut",
          "Engine 2 Vr-Cut",
          "Engine 1 V2-Cut",
          "Engine 2 V2-Cut",
          "Engine 1 Reverser",
          "Engine 2 Reverser",
        ],
      },
      {
        name: "Fire",
        events: [
          "Engine 1 Cowl Overheat",
          "Engine 2 Cowl Overheat",
          "Engine 1 Fire",
          "Engine 2 Fire",
          "APU Fire",
          "Forward Cargo Fire",
          "Aft Cargo Fire",
        ],
      },
      {
        name: "Fire Protection Systems",
        events: [
          "Engine 1 Fire Loop A",
          "Engine 2 Fire Loop A",
          "Engine 1 Fire Loop B",
          "Engine 2 Fire Loop B",
          "APU Fire Detection System",
          "Forward Cargo Fire Loop A",
          "Aft Cargo Fire Loop A",
          "Forward Cargo Fire Loop B",
          "Aft Cargo Fire Loop B",
          "Wheel Well Fire Detection Loop",
          "Bottle 1 Squib Left",
          "Bottle 1 Squib Right",
          "Bottle 2 Squib Left",
          "Bottle 2 Squib Right",
          "APU Bottle Squib",
          "Cargo Bottle Squib Forward",
          "Cargo Bottle Squib Aft",
          "Left Engine Fire Bottle Discharged",
          "Right Engine Fire Bottle Discharged",
          "APU Fire Bottle Discharged",
          "Cargo Fire Bottle 1 Discharged",
          "Cargo Fire Bottle 2 Discharged",
        ],
      },
      {
        name: "Flight Instruments",
        events: [
          "Display Unit Left Outboard (Captain's PFD)",
          "Display Unit Left Inboard (Captain's ND)",
          "Display Unit Upper (Engine Display)",
          "Display Unit Lower (Lower Center Display)",
          "Display Unit Right Inboard (FO's ND)",
          "Display Unit Right Outboard (FO's PFD)",
          "DEU 1",
          "DEU 2",
          "Standby ADI",
          "RMI",
        ],
      },
      {
        name: "Fuel",
        events: [
          "Left Forward Fuel Pump",
          "Left Aft Fuel Pump",
          "Center Left Fuel Pump",
          "Center Right Fuel Pump",
          "Right Forward Fuel Pump",
          "Right Aft Fuel Pump",
          "Fuel Leak",
          "Crossfeed Valve",
          "APU Fuel Valve",
          "Left Spar Valve",
          "Right Spar Valve",
          "Left Engine Valve",
          "Right Engine Valve",
        ],
      },
      {
        name: "Hydraulics",
        events: [
          "Engine Driven Pump (EDP) 1",
          "Engine Driven Pump (EDP) 2",
          "Electric Motor Driven Pump (EMDP) A",
          "Electric Motor Driven Pump (EMDP) B",
          "Standby Hydraulic Pump",
          "Engine Driven Pump (EDP) 1 Leak",
          "Engine Driven Pump (EDP) 2 Leak",
          "Electric Motor Driven Pump (EMDP) A Leak",
          "Electric Motor Driven Pump (EMDP) B Leak",
          "Standby Hydraulic Leak",
          "Electric Motor Driven Pump A Overheat",
          "Electric Motor Driven Pump B Overheat",
          "A SYS Quantity Refill Required",
          "B SYS Quantity Refill Required",
          "Standby System Quantity Refill Required",
        ],
      },
      {
        name: "Ice/Rain Protection",
        events: [
          "Captain's Pitot Heat",
          "Left Elevator Pitot Heat",
          "Left Alpha Vane Heat",
          "Temp Probe Heat",
          "Left Wing Anti Ice Valve",
          "Left Engine Anti Ice Valve",
          "Left Side Window Heat",
          "Left Front Window Heat",
          "Left Side Window Overheat",
          "Left Front Window Overheat",
          "FO Pitot Heat",
          "Right Elevator Pitot Heat",
          "Right Alpha Vane Heat",
          "Aux Pitot Heat",
          "Right Wing Anti Ice Valve",
          "Right Engine Anti Ice Valve",
          "Right Side Window Heat",
          "Right Front Window Heat",
          "Right Side Window Overheat",
          "Right Front Window Overheat",
        ],
      },
      {
        name: "Miscellaneous",
        events: [
          "Transponder 1",
          "Transponder 2",
          "TCAS",
          "Terrain Detection System",
          "Weather Radar System",
          "Weather Radar RT Left",
          "Weather Radar RT Right",
          "Windshear System",
          "Integrated Standby Flight Display",
          "Left Clock Fail",
          "Right Clock Fail",
        ],
      },
      {
        name: "Navigation",
        events: [
          "Flight Management Computer Left",
          "Flight Management Computer Right",
          "Inertial Reference System Left",
          "Inertial Reference System Right",
          "Inertial Reference System Display Unit",
          "GPS Left",
          "GPS Right",
          "Computer Display Unit Left",
          "Computer Display Unit Right",
          "ILS Left",
          "ILS Right",
          "VOR Left",
          "VOR Right",
          "DME Left",
          "DME Right",
          "ADF Left",
          "ADF Right",
          "Radio Altimeter Left",
          "Radio Altimeter Right",
        ],
      },
      {
        name: "Pneumatic",
        events: [
          "Engine 1 Bleed Over Temp",
          "Engine 2 Bleed Over Temp",
          "Engine 1 Bleed Over Pressure",
          "Engine 2 Bleed Over Pressure",
          "APU Bleed Valve",
          "Engine 1 Bleed PRSO Valve",
          "Engine 2 Bleed PRSO Valve",
          "Left Bleed Duct Leak",
          "Right Bleed Duct Leak",
          "Isolation Valve",
          "Left 9th Stage Bleed Valve",
          "Right 9th Stage Bleed Valve",
        ],
      },
      {
        name: "Pressurization",
        events: ["Pressure Hull Integrity", "Pax Oxygen Masks Deployed"],
      },
      {
        name: "Wheels and Brakes",
        events: [
          "Brake",
          "Tire",
          "Nose Tire Balance",
          "Antiskid Alternate Valve",
          "Antiskid Normal Valve",
          "Brake System Control Unit",
          "Brake Temperature System",
          "Autobrake Control System",
        ],
      },
    ],
  },
  {
    aircraft: "PMDG777",
    categories: [
      {
        name: "Active",
        events: [],
      },
      {
        name: "All Systems",
        events: [],
      },
      {
        name: "Air Conditioning",
        events: [
          "Cabin Temp Control Left",
          "Cabin Temp Control Right",
          "Pack Left Overheat",
          "Pack Right Overheat",
          "Pack Left Upper Flow Valve",
          "Pack Right Upper Flow Valve",
          "Pack Left Lower Flow Valve",
          "Pack Right Lower Flow Valve",
          "Trim Pressure Regulating Shut Off Valve Left",
          "Trim Pressure Regulating Shut Off Valve Right",
          "Recirc Fan Upper Forward",
          "Recirc Fan Upper Aft",
          "Recirc Fan Lower Left",
          "Recirc Fan Lower Right",
          "Air Cycle Machine Left",
          "Air Cycle Machine Right",
          "Equipment Clog Vent Fan",
          "Equipment Clog Supply Fan Left",
          "Equipment Clog Supply Fan Right",
          "Forward Outflow Valve Fail",
          "Aft Outflow Valve Fail",
          "Forward Outflow Valve Control",
          "Aft Outflow Valve Control",
          "Rapid Decompression",
          "Alt Vent"
        ],
      },
      {
        name: "APU",
        events: [
          "APU Air Turbine Starter",
          "APU Electric Starter",
          "APU Overheat",
          "APU Overspeed",
          "APU Oil Temperature",
          "APU Oil Pressure",
          "APU Oil Leak",
          "APU Bleed Air",
          "APU Inlet Door",
          "APU Severe",
        ],
      },
      {
        name: "Automatic Flight",
        events: [
          "Autothrottle INOP",
          "Left AFDC INOP",
          "Right AFDC INOP",
          "Center AFDC INOP",
          "AFS Failed",
        ],
      },
      {
        name: "Communications",
        events: [
          "Audio Control Panel Captain",
          "Audio Control Panel First Officer",
          "Audio Control Panel Observer",
          "Radio Tuning Panel Captain",
          "Radio Tuning Panel First Officer",
          "Radio Tuning Panel Observer",
          "VHF Left Radio Fail",
          "VHF Right Radio Fail",
          "VHF Center Radio Fail",
          "HF Left Radio Fail",
          "HF Right Radio Fail",
          "SATCOM System Fail",
        ],
      },
      {
        name: "Doors",
        events: [
          "Door 1 Left",
          "Door 1 Right",
          "Door 2 Left (PAX)",
          "Door 2 Right (PAX)",
          "Door 3 Left (PAX)",
          "Door 3 Right (PAX)",
          "Door 4 Left (PAX)",
          "Door 4 Right (PAX)",
          "Door 5 Left (300ER, if purchased and installed)",
          "Door 5 Right (300ER, if purchased and installed)",
          "Forward Cargo Door",
          "Aft Cargo Door",
          "Bulkhead Cargo Door",
          "Main Cargo Door (777F)",
          "RAT Deployed",
        ],
      },
      {
        name: "Electrical",
        events: [
          "Generator Left Fail",
          "Generator Right Fail",
          "APU Generator Fail",
          "Backup Generator Left Fail",
          "Backup Generator Right Fail",
          "All Engine Generators Fail",
          "Generator Left Drive Disconnect",
          "Generator Right Drive Disconnect",
          "Generator Left Breaker",
          "Generator Right Breaker",
          "AC Transfer Bus 1 Fail",
          "AC Transfer Bus 2 Fail",
          "AC Main Bus 1 Fail",
          "AC Main Bus 2 Fail",
          "AC Ground Servicing Bus Fail",
          "AC Ground Holding Bus Fail",
          "AC Utility Bus 1 Fail",
          "AC Utility Bus 2 Fail",
          "AC Standby Bus Fail",
          "Inverter Fail",
          "Transformer Rectifier Unit 1 Fail",
          "Transformer Rectifier Unit 2 Fail",
          "Transformer Rectifier Unit 3 Fail",
          "Transformer Rectifier Unit 4 Fail",
          "Ground Handling Transformer Rectifier Unit Fail",
          "Main Battery Charger Fail",
          "APU Battery Charger Fail",
          "Main Battery Fail",
          "APU Battery Fail",
          "DC Bus 1 Fail",
          "DC Bus 2 Fail",
          "Captain Flight Instrument Bus Fail",
          "First Officer Flight Instrument Bus Fail",
          "DC Hot Battery Bus Fail",
          "DC Main Battery Bus Fail",
          "DC Main2 Battery Bus Fail",
          "DC APU Battery Bus Fail",
        ],
      },
      {
        name: "Engine",
        events: [
          "EEC Mode 1",
          "EEC Mode 2",
          "Engine 1 Severe Damage",
          "Engine 2 Severe Damage",
          "Engine 1 Flame-out",
          "Engine 2 Flame-out",
          "Engine 1 EGT Exceedance",
          "Engine 2 EGT Exceedance",
          "Engine 1 Oil Leak",
          "Engine 2 Oil Leak",
          "Engine 1 Oil Pressure",
          "Engine 2 Oil Pressure",
          "Engine 1 Oil Temperature",
          "Engine 2 Oil Temperature",
          "Engine 1 Vibration",
          "Engine 2 Vibration",
          "Engine 1 V1 Cut",
          "Engine 2 V1 Cut",
          "Engine 1 Vr Cut",
          "Engine 2 Vr Cut",
          "Engine 1 V2 Cut",
          "Engine 2 V2 Cut",
          "Engine 1 Reverser",
          "Engine 2 Reverser",
        ],
      },
      {
        name: "Fire",
        events: [
          "APU Fire",
          "Forward Cargo Fire",
          "Aft Cargo Fire",
          "Engine Left Overheat",
          "Engine Right Overheat",
          "Engine Left Fire",
          "Engine Right Fire",
          "Main Deck Cargo Fire (777F)",
          "Equipment Cooling System Smoke",
          "Lavatory Smoke (PAX)",
          "Lavatory Smoke (Cargo)",
          "Smoke Rest Upper Door 1",
          "Smoke Rest Upper Door 4 (300ER, if purchased and installed)",
          "Smoke Rest Upper Door 5 (300ER, if purchased and installed)",
        ],
      },
      {
        name: "Fire Protection",
        events: [
          "Engine 1 Fire Loop A Fault",
          "Engine 2 Fire Loop A Fault",
          "Engine 1 Fire Loop B Fault",
          "Engine 2 Fire Loop B Fault",
          "Engine 1 Overheat Loop A Fault",
          "Engine 2 Overheat Loop A Fault",
          "Engine 1 Overheat Loop B Fault",
          "Engine 2 Overheat Loop B Fault",
          "APU Fire Loop A",
          "APU Fire Loop B",
          "Forward Cargo Fire Loop A",
          "Aft Cargo Fire Loop A",
          "Forward Cargo Fire Loop B",
          "Aft Cargo Fire Loop B",
          "Main Deck Fire Loop A (777F)",
          "Main Deck Fire Loop B (777F)",
          "Wheel Well Loop Fault A",
          "Wheel Well Loop Fault B",
          "Engine Bottle 1 Left Squib",
          "Engine Bottle 1 Right Squib",
          "Engine Bottle 2 Left Squib",
          "Engine Bottle 2 Right Squib",
          "APU Bottle Squib",
          "Cargo Dump Bottle 1 Squib",
          "Cargo Dump Bottle 2 Squib",
          "Cargo Meter Bottle 1 Squib",
          "Cargo Meter Bottle 2 Squib",
          "Cargo Meter Bottle 3 Squib",
          "Left Engine Fire Bottle Discharge",
          "Right Engine Fire Bottle Discharge",
          "APU Fire Bottle Discharge",
          "Cargo Dump Bottle 1 Discharge",
          "Cargo Dump Bottle 2 Discharge",
          "Cargo Meter Bottle 1 Discharge",
          "Cargo Meter Bottle 2 Discharge",
          "Cargo Meter Bottle 3 Discharge",
        ],
      },
      {
        name: "Flight Controls",
        events: [
          "PFCs to Secondary",
          "PFCs to Direct",
          "Actuator Control Electronics Left 1 Failed",
          "Actuator Control Electronics Right Failed",
          "Actuator Control Electronics Center Failed",
          "Actuator Control Electronics Left 2 Failed",
          "Flap/Slat Control 1 Fail",
          "Flap/Slat Control 2 Fail",
          "Spoiler Actuator 1 or 14 Fail",
          "Spoiler Actuator 2 or 13 Fail",
          "Spoiler Actuator 3 or 12 Fail",
          "Spoiler Actuator 4 or 11 Fail",
          "Spoiler Actuator 5 or 10 Fail",
          "Spoiler Actuator 6 or 9 Fail",
          "Spoiler Actuator 7 or 8 Fail",
          "Flaperon Actuator L1 Fail",
          "Flaperon Actuator L2 Fail",
          "Flaperon Actuator R1 Fail",
          "Flaperon Actuator R2 Fail",
          "Rudder Actuator 1 Fail",
          "Rudder Actuator 2 Fail",
          "Rudder Actuator 3 Fail",
          "Actuator Pressure Sensor Fail",
        ],
      },
      {
        name: "Flight Instruments",
        events: [
          "Display Unit Left Outboard Fail",
          "Display Unit Left Inboard Fail",
          "Display Unit Upper Fail",
          "Display Unit Lower Fail",
          "Display Unit Right Inboard Fail",
          "Display Unit Right Outboard Fail",
          "Digital Signal Processor Fail",
          "EFIS Control Panel Left Fail",
          "EFIS Control Panel Right Fail",
        ],
      },
      {
        name: "FMS/NAV/ADIRU",
        events: [
          "FMC Left Fail",
          "FMC Right Fail",
          "ADIRU Partial Fail",
          "ADIRU INOP/ Standby Attitude/Air Data Reference Unit ACT",
          "ADIRU/Standby Attitude/Air Data Reference Unit Attitude INOP",
          "ADIRU Single Channel",
          "ADIRU Air Data Invalid",
          "GPS Left Fail",
          "GPS Right Fail",
          "CDU Left Fail",
          "CDU Right Fail",
          "CDU Center Fail",
          "ILS Fail",
          "VOR Left Fail",
          "VOR Right Fail",
          "DME Left Fail",
          "DME Right Fail",
          "ADF Left Fail",
          "ADF Right Fail",
          "Radio Altimeter Left Fail",
          "Radio Altimeter Center Fail",
          "Radio Altimeter Right Fail",
        ],
      },
      {
        name: "Fuel",
        events: [
          "Left Forward Pump",
          "Left Aft Pump",
          "Left Jettison Pump",
          "Center Left Pump",
          "Center Right Pump",
          "Right Forward Pump",
          "Right Aft Pump",
          "Right Jettison Pump",
          "Fuel Leak",
          "Crossfeed Fail Forward",
          "Crossfeed Fail Aft",
          "Left Spar Valve",
          "Right Spar Valve",
          "Left Engine Valve",
          "Right Engine Valve",
          "APU Fuel Valve",
          "APU DC Fuel Pump",
          "Auxiliary Fuel Backup System",
          "Auxiliary Fuel Pump 1",
          "Auxiliary Fuel Pump 2",
          "Auxiliary Fuel Pump 3",
        ],
      },
      {
        name: "Hydraulic",
        events: [
          "EDP 1 Hydraulics Fail",
          "EDP 2 Hydraulics Fail",
          "ACMP C1 Hydraulics Fail",
          "ACMP C2 Hydraulics Fail",
          "ACMP Left Hydraulics Fail",
          "ACMP Right Hydraulics Fail",
          "ADP C1 Hydraulics Fail",
          "ADP C2 Hydraulics Fail",
          "EDP 1 Hydraulics Leak",
          "EDP 2 Hydraulics Leak",
          "ACMP C1 Hydraulics Leak",
          "ACMP C2 Hydraulics Leak",
          "ACMP Left Hydraulics Leak",
          "ACMP Right Hydraulics Leak",
          "ADP C1 Hydraulics Leak",
          "ADP C2 Hydraulics Leak",
          "EDP Left Overheat",
          "EDP Right Overheat",
          "ACMP C1 Overheat",
          "ACMP C2 Overheat",
          "ACMP Left Overheat",
          "ACMP Right Overheat",
          "ADP C1 Overheat",
          "ADP C2 Overheat",
          "Hydraulic Isolation Valve Left",
          "Hydraulic Isolation Valve Right",
          "Left System Quantity Refill Required",
          "Right System Quantity Refill Required",
          "Center System Quantity Refill Required",
          "System Data Left",
          "System Data Right",
          "System Data Center",
          "EDP Left Pressure XDCR Fail",
          "EDP Right Pressure XDCR Fail",
          "ACMP C1 Pressure XDCR Fail",
          "ACMP C2 Pressure XDCR Fail",
          "ACMP Left Pressure XDCR Fail",
          "ACMP Right Pressure XDCR Fail",
          "ADP C1 Pressure XDCR Fail",
          "ADP C2 Pressure XDCR Fail",
          "System Pressure Sensor Left Fail",
          "System Pressure Sensor Right Fail",
          "System Pressure Sensor Center Fail",
        ],
      },
      {
        name: "Ice Protection",
        events: [
          "Left Pitot Heat",
          "Left AOA Vane",
          "Left Ice Detection Fail",
          "TAT Probe Heat",
          "Left WAI Valve",
          "Left EAI Valve",
          "Left EAI Leak",
          "Left EAI Pressure Loss",
          "Left Side Window Heat",
          "Left Front Window Heat",
          "Left Side Window Overheat",
          "Left Front Window Overheat",
          "Right Pitot Heat",
          "Right AOA Vane",
          "Right Ice Detection Fail",
          "Right WAI Valve",
          "Right EAI Valve",
          "Right EAI Leak",
          "Right EAI Pressure Loss",
          "Right Side Window Heat",
          "Right Front Window Heat",
          "Right Side Window Overheat",
          "Right Front Window Overheat",
          "Center Pitot Heat",
        ],
      },
      {
        name: "Miscellaneous",
        events: [
          "Clock Left Fail",
          "Clock Right Fail",
          "ISFD Fail",
          "Passenger Oxygen Masks Deployed",
          "Standby Attitude Direction Indicator Fail",
          "Standby Airspeed Indicator Fail",
          "Standby Altimeter Fail",
          "Tail Strike",
          "Transponder 1 Fail",
          "Transponder 2 Fail",
        ],
      },
      {
        name: "Pneumatic",
        events: [
          "Left ASCP Controller",
          "Right ASCP Controller",
          "Left Engine HPSOV Valve",
          "Right Engine HPSOV Valve",
          "Left Engine PRSOV Valve",
          "Right Engine PRSOV Valve",
          "APU Bleed Valve",
          "Left Isolation Valve",
          "Right Isolation Valve",
          "Center Isolation Valve",
          "Bleed Air Leak",
        ],
      },
      {
        name: "Warning Systems",
        events: [
          "Altitude Alert System Fail",
          "Config Warning System Fail",
          "Ground Proximity Warning System Fail",
          "Terrain Warning System Fail",
          "TCAS Fail",
          "Weather Radar System Fail",
          "Weather Radar RT Left Fail",
          "Weather Radar RT Right Fail",
          "Predictive Windshear System Fail",
        ],
      },
      {
        name: "Wheels and Brakes",
        events: [
          "Brake Failure",
          "Tire Failure",
          "Nose Tire Balance",
          "Antiskid Alternate Valve",
          "Antiskid Normal Valve Left",
          "Antiskid Normal Valve Right",
          "Antiskid Transducer Left",
          "Antiskid Transducer Right",
          "Autobrake Isolation Valve",
        ],
      },
    ],
  },
  {
    aircraft: "Blacksquare Baron 58",
    categories: [
      {
        name: "Engine",
        events: [
          "L ENGINE FAILURE",
          "R ENGINE FAILURE",
          "L ENGINE FIRE",
          "R ENGINE FIRE",
          "L TURBOCHARGER",
          "R TURBOCHARGER",
          "L ENG DRIVEN OIL PUMP",
          "L ENG DRIVEN FUEL PUMP",
          "L UNFEATHERING ACCMLTR",
          "R ENG DRIVEN OIL PUMP",
          "R ENG DRIVEN FUEL PUMP",
          "R UNFEATHERING ACCMLTR",
          "L STARTER MOTOR",
          "R STARTER MOTOR",
          "L TACH AND FF GAUGES",
          "R TACH AND FF GAUGES",
          "L OIL AND CYL GAUGES",
          "R OIL AND CYL GAUGES",
          "ENGINE MONITOR",
          "PROP SYNC",
          "LOW THRUST DETECT",
        ],
      },
      {
        name: "Ignition",
        events: [
          "L ENG L MAGNETO",
          "L ENG R MAGNETO",
          "L ENG L MAGNETO GROUNDING",
          "L ENG R MAGNETO GROUNDING",
          "L IGNITION SWITCH GROUND",
          "R ENG L MAGNETO",
          "R ENG R MAGNETO",
          "R ENG L MAGNETO GROUNDING",
          "R ENG R MAGNETO GROUNDING",
          "R IGNITION SWITCH GROUND",
        ],
      },
      {
        name: "Electrical",
        events: [
          "L ALTERNATOR",
          "R ALTERNATOR",
          "ACCESSORIES POWER",
          "STANDBY AVIONICS",
          "VOLTMETER",
          "ANNUNCIATOR LIGHTS",
        ],
      },
      {
        name: "Flight Instruments",
        events: [
          "INSTRUMENT AIR",
          "INSTRUMENT AIR PARTIAL",
          "PITOT BLOCKAGE",
          "STATIC BLOCKAGE",
          "TURN COORD",
          "YOKE CHRONOS",
          "STALL WARNING",
        ],
      },
      {
        name: "Fuel",
        events: [
          "L FUEL LEAK",
          "R FUEL LEAK",
          "L FUEL PUMP",
          "R FUEL PUMP",
          "L FUEL QTY",
          "R FUEL QTY",
        ],
      },
      {
        name: "Brakes",
        events: ["L BRAKE", "R BRAKE"],
      },
      {
        name: "Landing Gear",
        events: ["GEAR MOTOR", "GEAR WARNING", "LANDING GEAR POS LIGHTS"],
      },
      {
        name: "Flight Controls",
        events: ["FLAP MOTOR"],
      },
      {
        name: "Pressurization",
        events: [
          "CABIN SAFETY VALVE",
          "CABIN OUTFLOW VALVE",
          "INFLOW CONTROL UNIT",
          "DOOR SEAL PRIMARY",
          "DOOR SEAL STANDBY",
          "CABIN PRESS CONTROL",
          "DOOR SEAL PUMP",
        ],
      },
      {
        name: "Environmental",
        events: [
          "L ENG CO LEAK",
          "R ENG CO LEAK",
          "CABIN HEATER CO LEAK",
          "CO DETECTOR",
          "COMBUSTION HEATER",
          "CONDENSER LIMIT",
          "VENT BLOWERS",
          "AIR CONDITIONER",
          "AIR CONDITIONING BLOWER",
          "CABIN HEAT IGN",
          "CABIN HEAT BLOWER",
        ],
      },
      {
        name: "Doors",
        events: ["NOSE DOOR LATCH", "PILOT DOOR LATCH", "CABIN DOOR LATCH"],
      },
      {
        name: "Ice Protection",
        events: [
          "DEICE BOOTS INTEG",
          "DEICE BOOTS",
          "L PITOT HEAT",
          "R PITOT HEAT",
          "PROP HEAT",
          "WINDSHIELD HEAT",
          "FUEL VENT HEAT",
          "STALL WARN HEAT",
        ],
      },
      {
        name: "Oxygen",
        events: ["OXYGEN LEAK"],
      },
      {
        name: "Lighting",
        events: [
          "STROBE LIGHT",
          "BEACON LIGHT",
          "NAV LIGHTS",
          "TAXI LIGHTS",
          "L LANDING LIGHTS",
          "R LANDING LIGHTS",
          "WING LIGHT",
          "PANEL LIGHTS",
          "CABIN LIGHTS",
        ],
      },
      {
        name: "Navigation",
        events: [
          "NAV 1",
          "NAV 2",
          "RNAV",
          "ADF",
          "HSI",
          "DME",
          "RADAR ALTIMETER",
          "REMOTE COMPASS",
          "GYRO SLAVING",
        ],
      },
      {
        name: "Communications",
        events: ["COM 1", "COM 2", "AUDIO PANEL", "TRANSPONDER"],
      },
      {
        name: "Autopilot",
        events: ["AUTOPILOT CONTROLLER", "AUTOPILOT ACTUATORS"],
      },
      {
        name: "Weather Systems",
        events: ["WX RADAR CONTROLLER", "WX RADAR TRANSCEIVER"],
      },
      {
        name: "Miscellaneous",
        events: ["ENCODER"],
      },
    ],
  },
  {
    aircraft: "Blacksquare Bonanza B36",
    categories: [
      {
        name: "Engine",
        events: [
          "ENGINE FAILURE",
          "ENGINE FIRE",
          "ENG DRIVEN OIL PUMP",
          "ENG DRIVEN FUEL PUMP",
          "STARTER MOTOR",
          "FUEL FLOW GAUGE",
          "TACHOMETER",
          "EGT/CHT",
          "OIL TEMP/PRESS",
          "ENGINE MONITOR",
        ],
      },
      {
        name: "Ignition",
        events: [
          "L MAGNETO",
          "R MAGNETO",
          "L MAGNETO GROUNDING",
          "R MAGNETO GROUNDING",
          "IGNITION SWITCH GROUND",
        ],
      },
      {
        name: "Electrical",
        events: [
          "ALTERNATOR",
          "STANDBY AVIONICS",
          "STANDBY ALT FIELD",
          "STANDBY ALT SENSE",
          "ACCESSORIES POWER",
          "VOLTMETER",
          "ANNUNCIATOR LIGHTS",
        ],
      },
      {
        name: "Flight Instruments",
        events: [
          "VACUUM PUMP",
          "VACUUM PUMP PARTIAL",
          "STANDBY VACUUM",
          "PITOT BLOCKAGE",
          "STATIC BLOCKAGE",
          "TURN COORD",
          "STALL WARNING",
          "YOKE CHRONOS",
        ],
      },
      {
        name: "Fuel",
        events: [
          "FUEL PUMP",
          "L TIP TANK X-FER PUMP",
          "R TIP TANK X-FER PUMP",
          "L FUEL LEAK",
          "R FUEL LEAK",
          "L TIP TANK LEAK",
          "R TIP TANK LEAK",
          "L FUEL QTY",
          "R FUEL QTY",
        ],
      },
      {
        name: "Brakes",
        events: ["L BRAKE", "R BRAKE"],
      },
      {
        name: "Landing Gear",
        events: ["GEAR MOTOR", "GEAR WARNING", "LANDING GEAR POS LIGHTS"],
      },
      {
        name: "Flight Controls",
        events: ["FLAP MOTOR"],
      },
      {
        name: "Environmental",
        events: [
          "CO LEAK",
          "CO DETECTOR",
          "CONDENSER LIMIT",
          "VENT BLOWERS",
          "AIR CONDITIONER",
          "AIR CONDITIONING BLOWER",
        ],
      },
      {
        name: "Doors",
        events: ["PILOT DOOR LATCH", "CABIN DOOR LATCH"],
      },
      {
        name: "Ice Protection",
        events: ["PITOT HEAT", "PROP HEAT"],
      },
      {
        name: "Oxygen",
        events: ["OXYGEN LEAK"],
      },
      {
        name: "Lighting",
        events: [
          "STROBE LIGHT",
          "BEACON LIGHT",
          "NAV LIGHTS",
          "TAXI LIGHTS",
          "LANDING LIGHTS",
          "PANEL LIGHTS",
          "CABIN LIGHTS",
        ],
      },
      {
        name: "Navigation",
        events: [
          "NAV 1",
          "NAV 2",
          "RNAV",
          "ADF",
          "HSI",
          "DME",
          "RADAR ALTIMETER",
          "REMOTE COMPASS",
          "GYRO SLAVING",
        ],
      },
      {
        name: "Communications",
        events: ["COM 1", "COM 2", "AUDIO PANEL", "TRANSPONDER"],
      },
      {
        name: "Autopilot",
        events: ["AUTOPILOT CONTROLLER", "AUTOPILOT ACTUATORS"],
      },
      {
        name: "Weather Systems",
        events: ["WX RADAR CONTROLLER", "WX RADAR TRANSCEIVER"],
      },
      {
        name: "Miscellaneous",
        events: ["ENCODER"],
      },
    ],
  },
  {
    aircraft: "Blacksquare Bonanza B36 (Turbine)",
    categories: [
      {
        name: "Engine",
        events: [
          "ENGINE FAILURE",
          "ENGINE FIRE",
          "PROPELLER GOVERNOR",
          "FUEL CONTROLLER",
          "ENGINE SURGE",
          "PRIMARY INJECTORS",
          "SECONDARY INJECTORS",
          "LP BLEED",
          "HP BLEED",
          "ENG DRIVEN FUEL PUMP",
          "STARTER MOTOR",
          "FUEL FLOW GAUGE",
          "ENGINE INSTRUMENTS",
          "ENGINE MONITOR",
          "TURBINE IGNITION",
        ],
      },
      {
        name: "Electrical",
        events: [
          "GENERATOR CONTROLLER",
          "STANDBY AVIONICS",
          "STANDBY ALT FIELD",
          "STANDBY ALT SENSE",
          "ACCESSORIES POWER",
          "VOLTMETER",
          "ANNUNCIATOR LIGHTS",
        ],
      },
      {
        name: "Flight Instruments",
        events: [
          "VACUUM PUMP",
          "VACUUM PUMP PARTIAL",
          "STANDBY VACUUM",
          "PITOT BLOCKAGE",
          "STATIC BLOCKAGE",
          "TURN COORD",
          "STALL WARNING",
          "YOKE CHRONOS",
        ],
      },
      {
        name: "Fuel",
        events: [
          "FUEL FILTER",
          "FUEL PUMP 1",
          "FUEL PUMP 2",
          "L FUEL LEAK",
          "R FUEL LEAK",
          "L FUEL QTY",
          "R FUEL QTY",
        ],
      },
      {
        name: "Brakes",
        events: ["L BRAKE", "R BRAKE"],
      },
      {
        name: "Landing Gear",
        events: ["GEAR MOTOR", "GEAR WARNING", "LANDING GEAR POS LIGHTS"],
      },
      {
        name: "Flight Controls",
        events: ["FLAP MOTOR"],
      },
      {
        name: "Pressurization",
        events: ["DOOR SEAL INTEG", "DOOR SEAL PUMP"],
      },
      {
        name: "Environmental",
        events: [
          "CO LEAK",
          "CO DETECTOR",
          "CONDENSER LIMIT",
          "VENT BLOWERS",
          "AIR CONDITIONER",
          "AIR CONDITIONING BLOWER",
        ],
      },
      {
        name: "Fire Protection",
        events: ["FIRE DETECTOR"],
      },
      {
        name: "Doors",
        events: ["PILOT DOOR LATCH", "CABIN DOOR LATCH"],
      },
      {
        name: "Ice Protection",
        events: ["ICE DEFLECTOR", "PITOT HEAT", "PROP HEAT"],
      },
      {
        name: "Oxygen",
        events: ["OXYGEN LEAK"],
      },
      {
        name: "Lighting",
        events: [
          "STROBE LIGHT",
          "BEACON LIGHT",
          "NAV LIGHTS",
          "TAXI LIGHTS",
          "LANDING LIGHTS",
          "PANEL LIGHTS",
          "CABIN LIGHTS",
        ],
      },
      {
        name: "Navigation",
        events: [
          "NAV 1",
          "NAV 2",
          "RNAV",
          "ADF",
          "HSI",
          "DME",
          "RADAR ALTIMETER",
          "REMOTE COMPASS",
          "GYRO SLAVING",
        ],
      },
      {
        name: "Communications",
        events: ["COM 1", "COM 2", "AUDIO PANEL", "TRANSPONDER"],
      },
      {
        name: "Autopilot",
        events: ["AUTOPILOT CONTROLLER", "AUTOPILOT ACTUATORS"],
      },
      {
        name: "Weather Systems",
        events: ["WX RADAR CONTROLLER", "WX RADAR TRANSCEIVER"],
      },
      {
        name: "Miscellaneous",
        events: ["ENCODER"],
      },
    ],
  },
];
